export const button = [
  { id: 22, value: '/' },
  { id: 1, value: '%' },
  { id: 2, value: '+-' },
  { id: 3, value: '.' },
  { id: 4, value: '+' },
  { id: 5, value: '-' },
  { id: 6, value: '*' },
  { id: 7, value: '(' },
  { id: 11, value: ')' },
  { id: 8, value: 7 },
  { id: 9, value: 8 },
  { id: 10, value: 9 },
  { id: 12, value: 4 },
  { id: 13, value: 5 },
  { id: 14, value: 6 },
  { id: 15, value: '=' },
  { id: 16, value: 1 },
  { id: 17, value: 2 },
  { id: 18, value: 3 },
  { id: 20, value: 0 },
  { id: 19, value: 'C' },
  { id: 21, value: 'CE' },
]
